spring.application.name=demo
# Change the MongoDB connection string here or set the MONGODB_URI environment variable.
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/simplebank}
spring.data.mongodb.database=simplebank
